data-quality-assessment/common.py
testing out pull requests through github
=> testing pull requests

dep-locate/dep_locate.py
=> Added stuff to locate and rawfiles

dep-locate/dep_locate.py, dep-locate/listInstrDirs.py, dep-locate/testListInstrDirs.py
I completed the python module to return a list of directory paths for the data disks of a given instrument.
I added a test module for it to test the list of paths. It asks the user for a keyword, checks it versus the valid keyword list, and then runs an ls command with each path in the directory list. otherwise it exits saying the keyword is invalid.
=> Completed new module to get directory listings. added a test module for it.

dep-locate/listInstrDirs.py, dep-locate/testListInstrDirs.py
the deimos filepath was configured slightly wrong, so I fixed it
NIRES wasn't added originally, so I added it now.
=> Fixed a bug with the deimos filepath. added NIRES to the list

data-quality-assessment/common.py, dep-locate/dep_locate.py
I made a cascading exception block to check if a keyword is valid. if it reaches the last block, the header is probably corrupted. It then logs the file and moves it to the anc_dir
=> rawfiles refactor and koaid testing

dep-locate/dep_locate.py
abstracted the logging and fits file move to its own function. function takes the instrument, file, anc directory and an error code which is based on where the file fails
=> moved error logging to a new function

dep-locate/dep_locate.py, dep-locate/listInstrDirs.py
abstracted the logging and fits file move to its own function. function takes the instrument, file, anc directory and an error code which is based on where the file fails
the portion of rawfiles that constructs a filename from the header data has been moved to its own function. 
I added a style of commenting similar to Javadoc/Doxygen that can be used with the Epydoc API from epydoc.sourceforge.net
=> made more functions. added a commenting style

dep-locate/dep_locate.py
still needs more work, but it's a lot more robust than I first thought. We can have multiple file handlers for different tasks.
=> Worked on the logging to make it work properly

dep-locate/dep_locate.py, dep-locate/writeLog.py
Starting to optimize the logger
Optimized the temporary filename creation
Optimized the code to check for .fits files and made it more pythonic
=> Optimized some things in dep-locate

deimos.py, esi.py, hires.py, instrument.py, lris.py, mosfire.py, nirc2.py, nirspec.py
instrument.py is the parent class
=> Started creating objects for the instruments

deimos.py, esi.py, hires.py, instrument.py, kcwi.py, lris.py, mosfire.py, nirc2.py, nires.py, nirspec.py, osiris.py
Apparently, python does not want me to explicitly call the superclass with parameters. children now init with all the parent class variables. I added a few more things to the parent and children. Parent now contains a 'origFile' variable for the fits files that contain a keyword their original file name. modified the date variable so it now populates with the current days date. we can change this if necessary
=> Added KCWI, NIRES, and OSIRIS classes. fixed the inheritance issue with the children classes. 

dep-locate/common.py, dep-locate/dep_locate.py
koaid updated to better handle differences in headers with UT/UTC/DATE keywords.
dep_locate added copy_file(), updated dep_rawfiles to remove "bad" filenames from fileList.
=> common.koaid and dep_locate updated

deimos.py, esi.py, hires.py, instrument.py, kcwi.py, lris.py, mosfire.py, nirc2.py, nires.py, nirspec.py, osiris.py
Default instruments (both parent and children) initialize with the current time if an endTime is not given.
I also went through and changed all the string concatenations to str.join() calls.
=> Added default endTime to instruments

deimos.py, dep-locate/dep_locate.py, esi.py, hires.py, instrument.py, kcwi.py, lris.py, mosfire.py, nirc2.py, nires.py, nirspec.py, osiris.py
Moved the log creation to its own method that runs during init.
Removed a member variable called keys because it was extraneous. All methods that use a fits header expect the header dict to be passed in as a parameter.
=> Minor adjustment

data-quality-assessment/dqa_run.py, dep-locate/oo_dep_locate.py, dep-obtain/dep_obtain.py, instrument.py
started working on converting dqa_run and dep-obtain to a procedural python script. Then I will convert them to an OO-style script
=> starting to work on dqa_run and dep-obtain

data-quality-assessment/dqa_run.py
The imagetyp_instr module and submodules have been ported from IDL to Py3
=> Finished moving imagetyp_instr from idl to py3

data-quality-assessment/dqa_run.py
Finished porting createprog.pro to python and got it tested on KOA ingested files. Need to test it on non-KOA files.
=> Finished createprog procedural function

data-quality-assessment/getProgInfo.py
* Finished converting ReadFileList()
* Finished assignToPi()
* Finished assignSingleToPi()
* Finished getScheduleValue()
=> Continued to convert getProgInfo to python. PyMySQL is working well.

dep-locate/dep_locate.py
Added more logging, changed logfile from debug.log, added KCWI in dep_rawfiles
=> dep_locate.py

data-quality-assessment/getProgInfo.py
This class will be deprecated once we move to the new system, but for now, it is in place.
=> finished splitprog class

dep-add/dep_add.py, dep-obtain/dep_obtain.py
Added log_writer to dep_add
dep_obtain completely new
=> dep_add and dep_obtain

create_prog.py, getProgInfo.py, instrument.py
create_prog
instrument
getProgInfo
=> getProgInfo updated and tested

dep_add.py, envlog.py, getProgInfo.py, instr_nires.py, instrument.py
instr_nires.py
getProgInfo.py
dep_add.py
envlog.py
instrument.py
=> Minor updates after testing through DQA

getProgInfo.py
Affected split nights for instruments without PROGNAMNE
=> Fixes to get_schedulem get_outdir, fix_outdir and datetime usage

dep_dqa.py, instr_nirspec.py, instrument.py
instr_nirspec - minor fixes
instrument - make_jpg updated to use os.walk
dep_dqa - gzipping updated to use os.walk
=> Few minor changes

instr_osiris.py
3% nonlinearity level (80% full well)
=> NONLIN keyword added

dep_dqa.py, instrument.py
small update to get instr to updateKoapiSend API call
=> hotfix pi send

dep_add.py, envlog.py, instrument.py
Took a bit longer than expected, got tangled up in some small details.  Review if you'd like or just approve and i'll release.
=> incorporate Epics archiver for weather keywords

dep_dqa.py, instr_deimos.py, instrument.py, metadata/keywords.format.DEIMOS
DEIMOS changes:  added file_size_mb and fixed issues with duplicate FCS files.
=> DEIMOS updates
